/*
 * //////////////////////////////////////////////////////////////////////////////
 * //
 * // Copyright © 2015-2021 Worldline SMB US Inc. All Rights Reserved.
 * //
 * //////////////////////////////////////////////////////////////////////////////
 */

#import <Foundation/Foundation.h>
#import "IMSTransactionHistorySummary.h"

/*!
 * This object contains summary of a invoice which can contain multiple transactions.
 */
@interface IMSInvoiceHistorySummary : NSObject

/*!
 * Reference for the Invoice generated by Ingenico Payment Server.
 */

@property (readonly) NSString *invoiceId;

/*!
 * The list of transactions that are part of this invoice.
 * @see IMSTransactionHistorySummary
 */

@property (readonly) NSArray *transactions;

- (id) initWithInvoiceID:(NSString *)invoiceId
         andTransactions:(NSArray *)transactions;

@end
