/*
 * //////////////////////////////////////////////////////////////////////////////
 * //
 * // Copyright © 2015-2021 Worldline SMB US Inc. All Rights Reserved.
 * //
 * //////////////////////////////////////////////////////////////////////////////
 */

#import "IMSBaseTransactionRequest.h"

/*!
 * This object contains information required for a void transaction.
 */

@interface IMSVoidTransactionRequest : IMSBaseTransactionRequest

/*!
 * Transaction ID of the original transaction generated by Ingenico Payment Server.
 */

@property (nonatomic, strong) NSString *originalSaleTransactionID;

/*!
 * Constructs a void request with mandatory fields that are common for all void transaction requests.
 * @param originalSaleTransactionID id of the transaction to reverse
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal;

/*!
 * Constructs a void request with mandatory fields that are common for all void transaction requests.
 * @param originalSaleTransactionID id of the transaction to reverse
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param customReference 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal andCustomReference:(NSString *)customReference;

/*!
 * Constructs a void request with mandatory fields that are common for all void transaction requests.
 * @param originalSaleTransactionID id of the transaction to reverse
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param customReference 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
 * @param transactionNotes transactionNotes
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal andCustomReference:(NSString *)customReference andTransactionNotes:(NSString *)transactionNotes;

/*!
 * Constructs a void request with mandatory fields that are common for all void transaction requests.
 * @param originalSaleTransactionID id of the transaction to reverse
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param customReference 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
 * @param transactionNotes transactionNotes
 * @param orderNumber Optional numeric field up to 9 digits long that indicates the assigned order number
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal andCustomReference:(NSString *)customReference andTransactionNotes:(NSString *)transactionNotes andOrderNumber:(NSString *)orderNumber;

/*!
 * Constructs a void request with mandatory fields that are common for all void transaction requests.
 * @param originalSaleTransactionID id of the transaction to reverse
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param customReference 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
 * @param transactionNotes transactionNotes
 * @param orderNumber Optional numeric field up to 9 digits long that indicates the assigned order number
 * @param showNotesAndInvoiceOnReceipt true - if transaction notes and merchant invoice id should be part of receipt
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal andCustomReference:(NSString *)customReference andTransactionNotes:(NSString *)transactionNotes andOrderNumber:(NSString *)orderNumber andShowNotesAndInvoiceOnReceipt:(bool)showNotesAndInvoiceOnReceipt;

@end
