/*
 * //////////////////////////////////////////////////////////////////////////////
 * //
 * // Copyright © 2015-2021 Worldline SMB US Inc. All Rights Reserved.
 * //
 * //////////////////////////////////////////////////////////////////////////////
 */

#import "IMSEnum.h"
#import "IMSCardholderInfo.h"
#import <Foundation/Foundation.h>

/*!
 * This object contains the basic information required for a transaction request.
 */

@interface IMSBaseTransactionRequest : NSObject

/*!
 * Reference for the Transaction generated by Ingenico SDK.
 */

@property (readonly) NSString *clientTransactionID;

/*!
 * ID reference used to associate the transaction with a waiter / clerk / sales associate. 
 * The field can be alphanumeric and length cannot exceed 4 characters
 */

@property (nonatomic, strong) NSString *clerkID;

/*!
 * TransactionType for base transaction request.
 * @see IMSTransactionType
 */

@property (nonatomic) IMSTransactionType transactionType;

/*!
 * Longitude
 */

@property (nonatomic, strong) NSString *gpsLong;

/*!
 * Latitude
 */

@property (nonatomic, strong) NSString *gpsLal;

/*!
 * Custom data
 */

@property (nonatomic, strong) NSString *customData;

/*!
 * Optional transaction notes.
 */

@property (nonatomic, strong) NSString *transactionNotes;

/*!
 * The invoice id from a third party inventory management tool linked to this transaction.
 * Alphanumeric characters only. Max length: 15 chars
 */

@property (nonatomic, strong) NSString *merchantInvoiceId;

/*!
 * Display transaction notes and merchant invoice number on the receipt.
 */

@property (nonatomic) bool showNotesAndInvoiceOnReceipt;

/*!
 * 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
 */

@property (nonatomic, strong) NSString *customReference;

/*!
 * Optional numeric field up to 9 digits long that indicates the assigned order number.
 */
@property (nonatomic, strong) NSString *orderNumber;

/*!
 * Transaction locale
 * Supported Locales: en_US, en_CA, fr_CA
 * Defaults to en_US if not set or unsupported locale is passed
 * Refer TransactionResponse.locale to see the final locale selected for the transaction
 */
@property (nonatomic, strong) NSLocale * _Nullable locale;

/*!
 * Constructs transaction request with mandatory fields that are common for all types of transaction requests.
 * @param type type of transaction
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 */

- (id) initWithType:(IMSTransactionType )type andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal;

/*!
 * Constructs transaction request with mandatory fields that are common for all types of transaction requests.
 * @param type type of transaction
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 */

- (id) initWithType:(IMSTransactionType )type andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal;

/*!
 * Constructs transaction request with mandatory fields that are common for all types of transaction requests.
 * @param type type of transaction
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionNotes transactionNotes
 * @param merchantInvoiceID The invoice id from a third party inventory management tool linked to this transaction.
 *                          Alphanumeric characters only. Max length: 15 chars
 * @param showNotesAndInvoiceOnReceipt true - if transaction notes and merchant invoice id should be part of receipt
 */

- (id) initWithType:(IMSTransactionType )type andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal andTransactionNotes:(NSString *)transactionNotes andMerchantInvoiceID:(NSString *)merchantInvoiceID andShowNotesAndInvoiceOnReceipt:(bool)showNotesAndInvoiceOnReceipt;

/*!
 * Constructs transaction request with mandatory fields that are common for all types of transaction requests.
 * @param type type of transaction
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionNotes transactionNotes
 * @param merchantInvoiceID The invoice id from a third party inventory management tool linked to this transaction.
 *                          Alphanumeric characters only. Max length: 15 chars
 * @param showNotesAndInvoiceOnReceipt true - if transaction notes and merchant invoice id should be part of receipt
 * @param customReference 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
 */

- (id) initWithType:(IMSTransactionType )type andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal andTransactionNotes:(NSString *)transactionNotes andMerchantInvoiceID:(NSString *)merchantInvoiceID andShowNotesAndInvoiceOnReceipt:(bool)showNotesAndInvoiceOnReceipt andCustomReference:(NSString *)customReference;

/*!
 * Constructs transaction request with mandatory fields that are common for all types of transaction requests.
 * @param type type of transaction
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionNotes transactionNotes
 * @param merchantInvoiceID The invoice id from a third party inventory management tool linked to this transaction.
 *                          Alphanumeric characters only. Max length: 15 chars
 * @param showNotesAndInvoiceOnReceipt true - if transaction notes and merchant invoice id should be part of receipt
 * @param customReference 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
 * @param orderNumber Optional numeric field up to 9 digits long that indicates the assigned order number
 */

- (id) initWithType:(IMSTransactionType )type andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal andTransactionNotes:(NSString *)transactionNotes andMerchantInvoiceID:(NSString *)merchantInvoiceID andShowNotesAndInvoiceOnReceipt:(bool)showNotesAndInvoiceOnReceipt andCustomReference:(NSString *)customReference andOrderNumber:(NSString *)orderNumber;

/*!
 * Constructs transaction request with mandatory fields that are common for all types of transaction requests.
 * @param type type of transaction
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionNotes transactionNotes
 * @param merchantInvoiceID The invoice id from a third party inventory management tool linked to this transaction.
 *                          Alphanumeric characters only. Max length: 15 chars
 * @param showNotesAndInvoiceOnReceipt true - if transaction notes and merchant invoice id should be part of receipt
 * @param customReference 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
 * @param orderNumber Optional numeric field up to 9 digits long that indicates the assigned order number
 * @param locale Transaction locale
 */

- (id) initWithType:(IMSTransactionType )type andClerkID:(NSString *)clerkID andLongitude:(NSString *)gpsLong andLatitude:(NSString *)gpsLal andTransactionNotes:(NSString *)transactionNotes andMerchantInvoiceID:(NSString *)merchantInvoiceID andShowNotesAndInvoiceOnReceipt:(bool)showNotesAndInvoiceOnReceipt andCustomReference:(NSString *)customReference andOrderNumber:(NSString *)orderNumber andLocale:(NSLocale *)locale;

@end
