/*
 * //////////////////////////////////////////////////////////////////////////////
 * //
 * // Copyright © 2015-2021 Worldline SMB US Inc. All Rights Reserved.
 * //
 * //////////////////////////////////////////////////////////////////////////////
 */

#import "IMSBaseSaleTransactionRequest.h"

@interface IMSCreditAuthCompleteTransactionRequest : IMSBaseSaleTransactionRequest

/*!
 * Transaction ID of the original sale transaction generated by Ingenico Payment Server.
 */

@property (nonatomic, strong) NSString *originalSaleTransactionID;

/*!
 * Constructs a credit auth complete request.
 * @param originalSaleTransactionID id of the previously requested credit auth transaction
 * @param amount final amount of the transaction
 * @param products list of products
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionGroupID a unique identifier for a group of transactions, used to link
 *                           transactions which are related (like split-tender).
 *                           If not specified in the request, it will be generated and returned in the response.
 *                           For linked transactions, the value generated from the first response
 *                           should be submitted with all related transactions.
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID
                               andAmount:(IMSAmount *)amount
                             andProducts:(NSArray *)products
                            andLongitude:(NSString *)gpsLong
                             andLatitude:(NSString *)gpsLal
                   andTransactionGroupID:(NSString *)transactionGroupID;

/*!
 * Constructs a credit auth complete request.
 * @param originalSaleTransactionID id of the previously requested credit auth transaction
 * @param amount final amount of the transaction
 * @param products list of products
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionGroupID a unique identifier for a group of transactions, used to link
 *                           transactions which are related (like split-tender).
 *                           If not specified in the request, it will be generated and returned in the response.
 *                           For linked transactions, the value generated from the first response
 *                           should be submitted with all related transactions.
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID
                               andAmount:(IMSAmount *)amount
                             andProducts:(NSArray *)products
                              andClerkID:(NSString *)clerkID
                            andLongitude:(NSString *)gpsLong
                             andLatitude:(NSString *)gpsLal
                   andTransactionGroupID:(NSString *)transactionGroupID;

/*!
* Constructs a credit auth complete request.
* @param originalSaleTransactionID id of the previously requested credit auth transaction
* @param amount final amount of the transaction
* @param products list of products
* @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
*                The field can be alphanumeric and length cannot exceed 4 characters.
* @param gpsLong longitude of the device location
* @param gpsLal latitude of the device location
* @param transactionGroupID a unique identifier for a group of transactions, used to link
*                           transactions which are related (like split-tender).
*                           If not specified in the request, it will be generated and returned in the response.
*                           For linked transactions, the value generated from the first response
 *                           should be submitted with all related transactions.
 * @param customReference 20 digit merchant order number (optional). Alphanumeric characters and hyphen only. Max length: 20.
*/

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID
                               andAmount:(IMSAmount *)amount
                             andProducts:(NSArray *)products
                              andClerkID:(NSString *)clerkID
                            andLongitude:(NSString *)gpsLong
                             andLatitude:(NSString *)gpsLal
                   andTransactionGroupID:(NSString *)transactionGroupID
                      andCustomReference:(NSString *)customReference;

/*!
 * Constructs a credit auth complete request.
 * @param originalSaleTransactionID id of the previously requested credit auth transaction
 * @param amount final amount of the transaction
 * @param products list of products
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionGroupID a unique identifier for a group of transactions, used to link
 *                           transactions which are related (like split-tender).
 *                           If not specified in the request, it will be generated and returned in the response.
 *                           For linked transactions, the value generated from the first response
 *                           should be submitted with all related transactions.
 * @param customReference 20 digit merchant order number (optional)
 * @param isCompleted indicates whether the transaction is completed,
 *                    if true the transaction cannot be updated later
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID
                               andAmount:(IMSAmount *)amount
                             andProducts:(NSArray *)products
                              andClerkID:(NSString *)clerkID
                            andLongitude:(NSString *)gpsLong
                             andLatitude:(NSString *)gpsLal
                   andTransactionGroupID:(NSString *)transactionGroupID
                      andCustomReference:(NSString *)customReference
                          andIsCompleted:(bool)isCompleted;

/*!
 * Constructs a credit auth complete request.
 * @param originalSaleTransactionID id of the previously requested credit auth transaction
 * @param amount final amount of the transaction
 * @param products list of products
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionGroupID a unique identifier for a group of transactions, used to link
 *                           transactions which are related (like split-tender).
 *                           If not specified in the request, it will be generated and returned in the response.
 *                           For linked transactions, the value generated from the first response
 *                           should be submitted with all related transactions.
 * @param customReference 20 digit merchant order number (optional)
 * @param isCompleted indicates whether the transaction is completed,
 *                    if true the transaction cannot be updated later
 * @param transactionNotes   transactionNotes
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID
                               andAmount:(IMSAmount *)amount
                             andProducts:(NSArray *)products
                              andClerkID:(NSString *)clerkID
                            andLongitude:(NSString *)gpsLong
                             andLatitude:(NSString *)gpsLal
                   andTransactionGroupID:(NSString *)transactionGroupID
                      andCustomReference:(NSString *)customReference
                          andIsCompleted:(bool)isCompleted
                          andTransactionNotes:(NSString *)transactionNotes;

/*!
 * Constructs a credit auth complete request.
 * @param originalSaleTransactionID id of the previously requested credit auth transaction
 * @param amount final amount of the transaction
 * @param products list of products
 * @param clerkID ID reference used to associate the transaction with a waiter / clerk / sales associate.
 *                The field can be alphanumeric and length cannot exceed 4 characters.
 * @param gpsLong longitude of the device location
 * @param gpsLal latitude of the device location
 * @param transactionGroupID a unique identifier for a group of transactions, used to link
 *                           transactions which are related (like split-tender).
 *                           If not specified in the request, it will be generated and returned in the response.
 *                           For linked transactions, the value generated from the first response
 *                           should be submitted with all related transactions.
 * @param customReference 20 digit merchant order number (optional)
 * @param isCompleted indicates whether the transaction is completed,
 *                    if true the transaction cannot be updated later
 * @param transactionNotes   transactionNotes
 * @param orderNumber        Optional numeric field up to 9 digits long that indicates the assigned order number
 */

- (id) initWithOriginalSaleTransactionID:(NSString *)originalSaleTransactionID
                               andAmount:(IMSAmount *)amount
                             andProducts:(NSArray *)products
                              andClerkID:(NSString *)clerkID
                            andLongitude:(NSString *)gpsLong
                             andLatitude:(NSString *)gpsLal
                   andTransactionGroupID:(NSString *)transactionGroupID
                      andCustomReference:(NSString *)customReference
                          andIsCompleted:(bool)isCompleted
                          andTransactionNotes:(NSString *)transactionNotes
                          andOrderNumber:(NSString *)orderNumber;

@end
