/*
 * //////////////////////////////////////////////////////////////////////////////
 * //
 * // Copyright © 2015-2021 Worldline SMB US Inc. All Rights Reserved.
 * //
 * //////////////////////////////////////////////////////////////////////////////
 */

#import <Foundation/Foundation.h>
#import "IMSEnum.h"

/*!
 * This object contains details of a pending transaction.
 */
@interface IMSPendingTransaction : NSObject

/*!
 * Reference for the Transaction generated by Ingenico mPOS SDK.
 */
@property (readonly) NSString *clientTransactionId;

/*!
 * The normalized total amount.
 */

@property (readonly) NSInteger totalAmount;

/*!
 * Subtotal amount of items being paid for in cents.
 */

@property (nonatomic) NSInteger subTotalAmount;

/*!
 * Tax amount charged in cents.
 */

@property (nonatomic) NSInteger taxAmount;

/*!
 * Discount amount in cents.
 */

@property (nonatomic) NSInteger discountAmount;

/*!
 * Tip amount in cents.
 */

@property (nonatomic) NSInteger tipAmount;

/*!
 * Discount description E.g. "Summer Sale".
 */
@property (nonatomic, strong) NSString *discountDescription;

/*!
 * ASCII representation of currency code.
 */

@property (nonatomic, strong) NSString *currency;

/*!
 * The point of sale entry mode.
 * @see IMSPOSEntryMode
 */

@property (readonly) IMSPOSEntryMode posEntryMode;

/*!
 * The transaction type.
 * @see IMSTransactionType
 */

@property (readonly) IMSTransactionType transactionType;

/*!
 * The time when the transaction was started.
 */

@property (readonly) NSString *createdTime;

/*!
 * The reason why reversal was attempted on the transaction.
 */

@property (readonly) IMSReversalReason reversalReason;

/*!
 * Surcharge amount in cents.
 */

@property (nonatomic) NSInteger surchargeAmount;



- (id) initWithClientTransactionId: (NSString *)clientTransactionId
                    andTotalAmount: (NSInteger)totalAmount
                  andSubtoalAmount: (NSInteger)subtotalAmount
                      andTaxAmount: (NSInteger)taxAmount
                 andDiscountAmount: (NSInteger)discountAmount
                      andTipAmount: (NSInteger)tipAmount
                       andCurrency: (NSString *)currency
            andDiscountDescription: (NSString *)discountDescription
                   andPosEntryMode: (IMSPOSEntryMode)posEntryMode
                andTransactionType: (IMSTransactionType)transactionType
                    andCreatedTime: (NSString *)createdTime
                 andReversalReason: (IMSReversalReason)reversalReason;

- (id) initWithClientTransactionId: (NSString *)clientTransactionId
                    andTotalAmount: (NSInteger)totalAmount
                  andSubtoalAmount: (NSInteger)subtotalAmount
                      andTaxAmount: (NSInteger)taxAmount
                 andDiscountAmount: (NSInteger)discountAmount
                      andTipAmount: (NSInteger)tipAmount
                andSurchargeAmount: (NSInteger)surchargeAmount
                       andCurrency: (NSString *)currency
            andDiscountDescription: (NSString *)discountDescription
                   andPosEntryMode: (IMSPOSEntryMode)posEntryMode
                andTransactionType: (IMSTransactionType)transactionType
                    andCreatedTime: (NSString *)createdTime
                 andReversalReason: (IMSReversalReason)reversalReason;
@end
