/*
 * //////////////////////////////////////////////////////////////////////////////
 * //
 * // Copyright © 2015-2021 Worldline SMB US Inc. All Rights Reserved.
 * //
 * //////////////////////////////////////////////////////////////////////////////
 */

#import <Foundation/Foundation.h>
#import "IMSAmount.h"
#import "IMSEnum.h"
#import "IMSTokenResponseParameters.h"

/*!
 * This object contains summary of a processed transaction.
 */
@interface IMSTransactionHistorySummary : NSObject

/*!
 * The transaction type.
 * @see IMSTransactionType
 */

@property (readonly) IMSTransactionType transactionType;

/*!
 * The point of sale entry mode.
 * @see IMSPOSEntryMode
 */

@property (readonly) IMSPOSEntryMode posEntryMode;

/*!
 * The response generated by Ingenico Payment Server.
 * i.e. Approved or Declined
 * @see IMSTransactionResponseCode
 */

@property (readonly) IMSTransactionResponseCode transactionResponseCode;

/*!
 * The card type.
 * @see IMSCardType
 */

@property (readonly) IMSCardType cardType;

/*!
 * The amount object.
 * @see IMSAmount
 */

@property (readonly) IMSAmount *amount;

/*!
 * Status of transaction
 * @see IMSTransactionStatus
 */

@property (readonly) IMSTransactionStatus transactionStatus;

/*!
 * The normalized approved amount.
 */

@property (readonly) NSInteger approvedAmount;

/*!
 * Reference for the transaction generated by Ingenico Payment Server.
 */

@property (readonly) NSString *transactionId;

/*!
 * ID reference used to associate the transaction with a waiter / clerk / sales associate.
 * The field can be alphanumeric and length cannot exceed 4 characters.
 */

@property (readonly) NSString *clerkId;

/*!
 * Introduced to support a feature in future release.
 */

@property (readonly) NSString *invoiceId;

/*!
 * The invoice id from a third party inventory management tool linked to this transaction.
 * Alphanumeric characters only. Max length: 15 chars
 */

@property (readonly) NSString *merchantInvoiceId;

/*!
 * Reference for the Transaction generated by Ingenico mPOS SDK.
 */

@property (readonly) NSString *clientTransactionId;

/*!
 * Reference for the original transaction generated by Ingenico Payment Server,
 * in case of refund or void transactions.
 */

@property (readonly) NSString *originalTransactionId;

/*!
 * The message which was displayed on merchant's device/console.
 */

@property (readonly) NSString *clerkDisplay;

/*!
 * The redacted card number. Eg: 1234XXXXXXXX5678.
 */

@property (readonly) NSString *redactedCardNumber;

/*!
 * Transaction notes.
 */

@property (readonly) NSString *transactionNote;

/*!
 * The timestamp recorded by the processor.
 */

@property (readonly) NSString *processorTimestamp;

/*!
 * The timezone the processor is in.
 */

@property (readonly) NSString *processorTimezone;

/*!
 * The timestamp recorded by the mobile device.
 */

@property (readonly) NSString *deviceTimestamp;

/*!
 * The timezone the mobile device is in.
 */

@property (readonly) NSString *deviceTimezone;

/*!
 * The timestamp recorded by Ingenico Payment Services.
 */

@property (readonly) NSString *paymentServiceTimestamp;

/*!
 * The timezone the server hosting Ingenico Payment Services is in.
 */

@property (readonly) NSString *paymentServiceTimezone;

/*!
 * The result of the token request, if present.
 * Note: [IMSTokenResponseParameters tokenSourceData] will be nil
 * In order to have this data included, set [IMSHistoryQueryBuilder optionalFields] to contain [IMSOptionalTransactionHistoryField OptionalFieldTokenData]
 */
@property (readonly) IMSTokenResponseParameters *tokenResponse;

/*!
 * GUID Reference for the transaction generated by Ingenico Payment Services.
 */
@property (readonly) NSString *transactionGUID;

/*!
 * The source of this transaction
 */
@property (readonly) IMSPOSEntrySource posEntrySource;

- (id) initWithTransactionType:(IMSTransactionType)transactionType
               andPosEntryMode:(IMSPOSEntryMode)posEntryMode
    andTransactionResponseCode:(IMSTransactionResponseCode)transactionResponseCode
                   andCardType:(IMSCardType)cardType
                     andAmount:(IMSAmount *)amount
          andTransactionStatus:(IMSTransactionStatus)transactionStatus
             andApprovedAmount:(NSInteger)approvedAmount
                    andClerkId:(NSString *)clerkId
                  andInvoiceId:(NSString *)invoiceId
          andMerchantInvoiceId:(NSString *)merchantInvoiceId
              andTransactionId:(NSString *)transactionId
        andClientTransactionId:(NSString *)clientTransactionId
      andOriginalTransactionId:(NSString *)originalTransactionId
               andClerkDisplay:(NSString *)clerkDisplay
         andRedactedCardNumber:(NSString *)redactedCardNumber
            andTransactionNote:(NSString *)transactionNote
         andProcessorTimestamp:(NSString *)processorTimestamp
          andProcessorTimezone:(NSString *)processorTimezone
            andDeviceTimestamp:(NSString *)deviceTimestamp
             andDeviceTimezone:(NSString *)deviceTimezone
    andPaymentServiceTimestamp:(NSString *)paymentServiceTimestamp
     andPaymentServiceTimezone:(NSString *)paymentServiceTimezone
    andTokenResponseParameters:(IMSTokenResponseParameters *)tokenResponse;

- (id) initWithTransactionType:(IMSTransactionType)transactionType
               andPosEntryMode:(IMSPOSEntryMode)posEntryMode
    andTransactionResponseCode:(IMSTransactionResponseCode)transactionResponseCode
                   andCardType:(IMSCardType)cardType
                     andAmount:(IMSAmount *)amount
          andTransactionStatus:(IMSTransactionStatus)transactionStatus
             andApprovedAmount:(NSInteger)approvedAmount
                    andClerkId:(NSString *)clerkId
                  andInvoiceId:(NSString *)invoiceId
          andMerchantInvoiceId:(NSString *)merchantInvoiceId
              andTransactionId:(NSString *)transactionId
        andClientTransactionId:(NSString *)clientTransactionId
      andOriginalTransactionId:(NSString *)originalTransactionId
               andClerkDisplay:(NSString *)clerkDisplay
         andRedactedCardNumber:(NSString *)redactedCardNumber
            andTransactionNote:(NSString *)transactionNote
         andProcessorTimestamp:(NSString *)processorTimestamp
          andProcessorTimezone:(NSString *)processorTimezone
            andDeviceTimestamp:(NSString *)deviceTimestamp
             andDeviceTimezone:(NSString *)deviceTimezone
    andPaymentServiceTimestamp:(NSString *)paymentServiceTimestamp
     andPaymentServiceTimezone:(NSString *)paymentServiceTimezone
    andTokenResponseParameters:(IMSTokenResponseParameters *)tokenResponse
            andTransactionGUID:(NSString *)transactionGUID
              andPOSEntrySource:(IMSPOSEntrySource)posEntrySource;
@end
